[2024-08-20 22:42:51,020] 18 root - INFO - data loading started...
[2024-08-20 22:42:51,148] 21 root - INFO - data loading completed...
[2024-08-20 22:42:56,353] 38 root - ERROR - An error occurred: Error occured in python script name [C:\Users\DELL\qasystemnew\QAWithPDF\model_api.py] line number [30] error message [403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "generativelanguage.googleapis.com"
}
metadata {
  key: "method"
  value: "google.ai.generativelanguage.v1beta.ModelService.GetModel"
}
]]
